export const GAME_STARTED = "GAME_STARTED";
export const GAME_RESET = "GAME_RESET";
export const START_COUNTDOWN = "START_COUNTDOWN";
export const STOP_COUNTDOWN = "STOP_COUNTDOWN";
export const RESET_COUNTDOWN = "RESET_COUNTDOWN";
export const SURRENDER_GAME = "SURRENDER_GAME";
export const ATTACK_NORMAL = "ATTACK_NORMAL";
export const ANOUNCE_WINNER = "ANOUNCE_WINNER";
