export const GAME_STARTED = "GAME_STARTED";
export const SET_GAME_TIME = "SET_GAME_TIME";
export const START_COUNTDOWN = "START_COUNTDOWN";
export const RESET_COUNTDOWN = "RESET_COUNTDOWN";
export const SURRENDER_GAME = "SURRENDER_GAME";
